kiss:
   voxel_size: 1
   max_range: 100
   min_range: 1
   max_points_per_voxel: 20
   min_motion_th: 0.1
   initial_threshold: 2.0
   deskew: ture
   
common:          
   cut_frame: false        
   cut_frame_num: 2
   lidar_topic: "/livox/lidar"       
   image_topic: "/camera/image_color/compressed"    
   child_frame: "base_link"
   odom_frame: "odom"

kiss_vio:
   en_cam: true   
   image_height: 1024        
   image_weight: 1280   
   distCoeffs: [-0.1080, 0.1050, -1.2872e-04, 5.7923e-05, 0] 
   # Fine extrinsic value. form camera-LiDAR calibration.
   intrisicMat:
      [863.4241, 0.0, 640.6808,
      0.0,  863.4171, 518.3392,
      0.0, 0.0, 1.0 ] 

   extrinsicMat_RT:
         [0.0158682,-0.999874, -0.00050462, 0.0,
           -0.00113994,  -0.00048659,  -0.9999999, 0.0,
            0.999873,  0.0158688,  -0.00113207, 0.0,
            0.0, 0.0, 0.0, 1.0]

